- name: install python library dependencies
  ansible.builtin.pip:
    executable: pip3.9
    name: "{{ item }}"
  loop:
  - cryptography
  - PyMySQL
- name: setup the {{ component }} module
  ansible.builtin.import_role:
    name: common
    tasks_from: java
- name: import shipping schemas to mysql Database
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: mysql.devsecops86s.space
    login_user: root
    login_password: RoboShop@1
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql
- name: setup the {{ component }} module
  ansible.builtin.import_role:
    name: common
    tasks_from: service_setup