  - name: install the maven and mysql
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql
  - name: install python library dependencies
    ansible.builtin.pip:
      executable: pip3.9
      name: "{{ item }}"
    loop:
    - cryptography
    - PyMySQL
  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: " create system user"
      system: true
      shell: /sbin/nologin
      home: /app
  - name: remove the existing /app directory
    ansible.builtin.file:
      path: /app
      state: absent
  - name: create the /app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: remove the /tmp/shipping.zip directory
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent
  - name: download the shipping app code to /tmp/shipping.zip directory
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip"
      dest: /tmp/shipping.zip
  - name: unarchive the zip folder to /app
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes
  - name: install maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app
  - name: rename the file shipping-1.0.jar to shipping.jar
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app
  - name: copy the shipping.service to systemd path
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
  - name: import shipping schemas to mysql Database
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: mysql.devsecops86s.space
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql
  - name: reload and start the service
    ansible.builtin.systemd_service:
      name: shipping
      daemon_reload: true
      enabled: yes
      state: started