- name: Setup the nodejs app
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs_app_setup
- name: copy the mongo.repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: install mongosh client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present
- name: evaluate the catalog in DB
  ansible.builtin.command: mongosh --host mongodb.devsecops86s.space --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

- name: print the catalogue_output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load the catalog products to mongo Db if there is product data
  ansible.builtin.shell: mongosh --host mongodb.devsecops86s.space </app/db/master-data.js
  when: catalogue_output.stdout | int < 0
  
- name: Setup the service setup
  ansible.builtin.import_role:
    name: common
    tasks_from: service_setup
