- name: copy the catalogue.service to /etc/systemd/system
  ansible.builtin.copy:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service
  notify: daemon-reload
- name: start and enable service 
  ansible.builtin.systemd_service:
    name: "{{ component }}"
    state: started
    enabled: yes